spring:
  application:
    name: authentication-server
---
spring:
  r2dbc:
    url: r2dbc:proxy:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres

---