spring:
  application:
    name: authentication-server
---
spring:
  cassandra:
    compression: lz4
    schema-action: create_if_not_exists
    local-datacenter: datacenter1
    keyspace-name: auth
---
logging:
  level:
    org:
      springframework: debug