spring:
  application:
    name: authentication-server
---
spring:
  cassandra:
    compression: none
    schema-action: create_if_not_exists
    local-datacenter: datacenter1
    keyspace-name: auth
---