version: "3.9"

services:
  authdb:
    container_name: authdb
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: on-failure

  redis:
    container_name: redis
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: on-failure
