apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: infra
deploy:
  helm:
    releases:
      - name: graphql-mesh
        recreatePods: false
        skipBuildDependencies: true
        useHelmSecrets: false
        wait: true
        namespace: gateway
        createNamespace: true
        chartPath: deployments/helm/gateway/graphql-mesh

        