apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: backend
profiles:
  - name: backend
    activation:
      - kubeContext: minikube
        env: ACTIVATE_MONITORING=true
        command: local
deploy:
  helm:
    releases:
      - name: upload-service
        recreatePods: false
        skipBuildDependencies: true
        useHelmSecrets: false
        wait: true
        namespace: backend
        createNamespace: true
        chartPath: deployments/helm/backend/test-service