apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: monitoring
profiles:
  - name: monitoring
    activation:
      - kubeContext: minikube
        env: ACTIVATE_MONITORING=true
        command: local
deploy:
  helm:
    releases:
      - name: prometheus
        recreatePods: false
        skipBuildDependencies: true
        useHelmSecrets: false
        wait: true
        namespace: monitoring
        createNamespace: true
        chartPath: deployments/helm/monitoring/prometheus
      - name: jaeger-all-in-one
        skipBuildDependencies: true
        useHelmSecrets: false
        wait: true
        namespace: monitoring
        chartPath: deployments/helm/monitoring/jaeger-all-in-one
      - name: opentelemetry-collector
        recreatePods: false
        skipBuildDependencies: true
        useHelmSecrets: false
        wait: true
        namespace: monitoring
        createNamespace: true
        chartPath: deployments/helm/monitoring/opentelemetry-collector
      - name: grafana
        recreatePods: false
        skipBuildDependencies: true
        useHelmSecrets: false
        wait: true
        namespace: monitoring
        createNamespace: true
        chartPath: deployments/helm/monitoring/grafana