apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: gateway
profiles:
  - name: gateway
    activation:
      - kubeContext: minikube
        env: ENV=local
        command: local
deploy:
  helm:
    releases:
      - name: istio-base
        remoteChart: base
        repo: https://istio-release.storage.googleapis.com/charts
        namespace: istio-system
        createNamespace: true
      - name: istio-gateway
        recreatePods: false
        skipBuildDependencies: true
        useHelmSecrets: false
        wait: true
        namespace: istio-system
        createNamespace: true
        chartPath: deployments/helm/gateway/istio
      - name: cert-manager
        remoteChart: cert-manager
        repo: https://charts.jetstack.io
        version: v1.11.0
        namespace: cert-manager
        createNamespace: true
        wait: true
        setValueTemplates:
          installCRDs: true
