apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: infra
deploy:
  helm:
    releases:
      - name: redis
        recreatePods: false
        skipBuildDependencies: false
        useHelmSecrets: false
        wait: false
      - name: istio-gateway
      