# To learn more about the skaffold.yaml schema visit
# https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: dev
requires:
  - path: skaffold.monitoring.yaml
  - path: skaffold.infra.yaml
build:
  local:
    concurrency: 1
    tryImportMissing: false
    useDockerCLI: false
profiles:
- name: cloudbuild
  build:
    googleCloudBuild: {}
