sources:
  - name: AuthService
    handler:
      openapi:
        source: "{env.AUTH_SERVICE}/v3/api-docs"
        endpoint: "{env.AUTH_SERVICE}"
        ignoreErrorResponses: true

serve:
  hostname: 0.0.0.0
  cors:
    credentials: true
