openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /accounts/verify-account:
    post:
      tags:
        - accounts
      summary: Perform verify account action.
      operationId: verifyAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/VerifyAccountDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/ResponseString"
  /accounts/challenge:
    post:
      tags:
        - accounts
      summary: Perform challenge nonce for verifying account.
      operationId: challenge
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChallengeDto"
        required: true
      responses:
        "200":
          description: OK
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/ResponseString"
components:
  schemas:
    VerifyAccountDto:
      required:
        - address
        - message
        - signature
      type: object
      properties:
        address:
          type: string
        message:
          type: string
        signature:
          type: string
    ResponseString:
      required:
        - status
      type: object
      properties:
        status:
          type: integer
          format: int32
        data:
          type: string
    ChallengeDto:
      required:
        - address
      type: object
      properties:
        address:
          type: string
