apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: api-falsy
  labels:
    {{- include "cert-manager.labels" . | nindent 4 }}
spec:
  acme:
    skipTLSVerify: true
    privateKeySecretRef:
      name: pk-{{ include "cert-manager.fullname" . }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: user@example.com
  solvers:
    - http01:
        ingress:
          class: istio