appVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "upload-service.fullname" . }}
  labels:
    {{- include "upload-service.labels" . | nindent 4 }}
data:
  database.url: "localhost:5432"
  database.user: "myuser"
  database.password: "mypassword"