spring:
  application:
    name: account-service
---
spring:
  cassandra:
    compression: none
    schema-action: create_if_not_exists
    local-datacenter: datacenter1
    keyspace-name: account
    contact-points: 127.0.0.1:9042
---
