spring:
  application:
    name: account-service
---
spring:
  cassandra:
    compression: lz4
    schema-action: create-if-not-exists
    local-datacenter: ${DATA_CENTER}
    keyspace-name: ${KEYSPACE}
    contact-points: ${CONTACT_POINTS}
---
logging:
  level:
    org:
      springframework: debug
