version: "3.9"

services:
  accountdb:
    container_name: accountdb
    image: mysql:latest@sha256:a43f6e7e7f3a5e5b90f857fbed4e3103ece771b19f0f75880f767cf66bbb6577
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: account-database
      MYSQL_USER: account-user
      MYSQL_PASSWORD: P@ssw0rd
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    restart: on-failure

  redis:
    container_name: redis
    image: redis/redis-stack@sha256:f32efb09d1e4f87997470efb444e8810788a5c558900a80ee562f2be5d64b481
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: on-failure

  ## Service
  account-service:
    container_name: account-service
    image: falsyoss/account-service:latest
    build:
      context: account-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - accountdb
    env_file:
      - ./account-service/dev.env
    restart: on-failure

  gateway:
    container_name: gateway
    image: falsyoss/gateway:latest
    build:
      context: gateway
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true
    volumes:
      - ./gateway/.meshrc.yml:/usr/src/app/.meshrc.yml
    depends_on:
      - account-service
    env_file: ./gateway/dev.env
    restart: on-failure

  marketplace:
    container_name: marketplace
    image: falsyoss/marketplace:latest
    build:
      context: marketplace
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - gateway
    env_file: ./marketplace/dev.env
    restart: on-failure
